name: e2e

on:
  push:
    branches: [main]
    paths-ignore:
      - "artifacts/**"

jobs:
  build:
    name: Optimized Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install cargo-run-script
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-run-script
      - name: Run cargo optimize
        uses: actions-rs/cargo@v1
        with:
          command: run-script
          args: optimize
      - name: Change Artifact Permissions
        run: |
          sudo chown -R 1001:116 ./artifacts/*
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./artifacts
          git commit -m "ci: created optimized build" -a
          git push
